Monocle Layout "minimize others" only on same monitor
gikari/bismuth pull request #45
Opened 2021-09-22 00:42 UTC by bladedvox

closes #43
Pretty simple fix, just checks that the window is in the same monitor before minimizing for that feature.

2021-09-22 10:42 UTC, gikari commented on src/engine/layout/monocle_layout.ts
> +              && (window.window as KWinWindow).client.screen
It's better to move the screen getter and minimized property into the window interface:
```typescript
export default class Window {
// ...
public get screenNumber(): number {
    return this.window.screenNumber;
}
// ...
}
```
This avoids casting and respects [SOLID](https://en.wikipedia.org/wiki/SOLID).

2021-09-22 10:47 UTC, gikari commented
Could you also change your commit messages to respect [CC](https://www.conventionalcommits.org/en/v1.0.0/)? I should probably implement CI check for this in the future.

2021-09-22 17:22 UTC, bladedvox commented on src/engine/layout/monocle_layout.ts
> +              && (window.window as KWinWindow).client.screen
Ok, I got it to build changing as you suggested, I will test tonight and reopen if it works properly.

2021-09-25 17:26 UTC, bladedvox commented
@gikari I've got the original functionality restored. It's kind of hacky but the only way I could find to do it. Basically I added a hook to `controller.onWindowFocused()` to do the minimization under the correct layout (and if the setting is enabled). I also had `controller.showNotification()` raise the event as well so that it works properly when first changing to the Monocle layout.

How do you want to handle the finer points?
* Should we enable this by default?
* Should we make an exception for the focus cycle (or add a separate Action) that includes minimized windows in the queue when switching focus?

2021-09-26 12:20 UTC, gikari requested changes
> Should we enable this by default?

Not yet. If it works well - we probably should in the future.

> Should we make an exception for the focus cycle (or add a separate Action) that includes minimized windows in the queue when switching focus?

We have FocusNextWindow and FocusPreviousWindow. Those should work with this option on as in before. As for Focus Left, Right and so on, I am not sure. How do those work in classic tilings WMs with monocle layout (It seems like Monocle is the terminology, that comes from dwm)?

2021-09-26 12:20 UTC, gikari commented on src/controller/index.ts
> +    if (this.engine.currentLayoutOnCurrentSurface() instanceof MonocleLayout &&
This is the "business logic" of tiling. It needs to be inside the engine. The controller is responsible only for input and events handling and sometimes the validation of the data from the driver. It is similar to MVC pattern (or MVVM) - the controller is a middleman between the model (in our case engine) and the view (in our case the driver).

2021-09-26 16:33 UTC, bladedvox commented on src/controller/index.ts
> +    const self = this;
Ah, that was left over from a previous attempt at implementing. Good catch, it isn't necessary anymore.

2021-09-26 16:34 UTC, bladedvox commented on src/controller/index.ts
> +    if (this.engine.currentLayoutOnCurrentSurface() instanceof MonocleLayout &&
Ok, I'll move it into an `engine` method.

2021-09-26 16:57 UTC, bladedvox commented
I will address the comments you raised today -- as for the keyboard shortcuts, it's been a long time since I used DWM, but looking at the source code now it seems that it doesn't implement minimization at all. I currently like the behavior we have of cycling only through visible windows with the `FocusNext/PrevWindow` actions. I use a keybind for a task switcher that cycles through minimized windows only if I need to quickly get access to one, and is how I currently switch focus by keyboard in Monocle mode with the `monocleMinimizeRest` option enabled.

I think, just to avoid needing a separate keyboard shortcut, we should either
a. include minimized windows for consideration in `FoucsNext/Prev`
b. add an optional argument to `engine.focusOrder()` that is used in MonocleLayout (when this option is enabled) when overriding `FocusNext/Prev/Bottom/Upper/Left/Right` that includes minimized windows for consideration

I lean towards `b` since I like the current focus switching model.

2021-09-26 17:06 UTC, gikari commented
>  it's been a long time since I used DWM, but looking at the source code now it seems that it doesn't implement minimization at all. 

I meant if the switching between windows in monocle mode works with Next/Previous window shortcuts. If it is, we should do the same, but we can provide an option to exclude minimized windows from the list.

2021-09-27 02:30 UTC, bladedvox commented
Using this branch on my machine and so far so good. Here's some notes on the behavior:

Assuming monocle layout and `config.monocleMinimizeRest == true`:
* You can switch windows with the `WindowFocusNext/Prev/Right/Left/Upper/Bottom` Actions
* Closing the active window switches to the next window
* Floating windows on the `DriverSurface` are handled properly
* Moving a tiled window into the workspace/screen results in it being the only visible window
There is still an issue with using this layout in a multi-monitor setup -- if you close the active window in Monocle layout in your secondary monitor, it switches to a window in the primary monitor instead of the same monitor that the closed window was in. I Haven't really figured out why this is happening. I have some code that *tries* to fix it but it isn't really working. Will update with progress on that. Other than that minor issue, I am comfortable with the experience so far.

2021-09-29 22:46 UTC, bladedvox commented
I see the failing tests. Edited the `action.test` locally and will rebase/reword to shorten my commit messages.

2021-09-29 22:48 UTC, gikari commented
> I see the failing tests. Edited the `action.test` locally and will rebase/reword to shorten my commit messages.

Could you also please update the MR description according to the [new template](https://github.com/gikari/bismuth/blob/master/.github/pull_request_template.md) please?

2021-09-29 22:59 UTC, bladedvox commented
PR description updated, hope it's all up to standard :)

2021-09-29 23:58 UTC, gikari requested changes
Awesome! :tada: I just tested, and it works very well (except after closing a window in multimonitor it focuses the one, on the other monitor, so after merging you could create an issue for this strange behavior). Just a little small nitpicks (including in-code comments):

I think you can remove WIP it the UI. It still has the multimonitor problem, but I think it works good to be considered WIP feature, and in general marking something WIP in the UI lies not a good impression on the end user.

Also, I apologize for some pasts of CI not working as intended right now. So, could you please format your code with prettier?

And you need to rebase your branch on the current master.

2021-09-29 23:58 UTC, gikari commented on src/controller/index.ts
> +      this.engine.currentLayoutOnCurrentSurface().apply(
Why do we need to reapply layout?

2021-09-29 23:58 UTC, gikari commented on src/engine/index.ts
> +  focusOrder(step: -1 | 1, includeHidden: boolean): void;
In the future, I'm planning to move the JSDoc comments to the interface. Since you're adding the new parameter, could you add the comment here with the params description?

2021-09-29 23:58 UTC, gikari commented on src/engine/index.ts
> +        && this.config.monocleMinimizeRest && this.controller.currentWindow) {
```typescript
this.currentLayoutOnCurrentSurface() instanceof MonocleLayout && this.config.monocleMinimizeRest
```
is very commonly used. Maybe it is worth creating a wrapper in the engine? Or may be not, because in the future, it will be a good idea to make layouts have their own handlers of events, like `onActivate`, where it will do the layout specific logic, and those hacky checks will go away. What do you think?

2021-09-30 00:27 UTC, bladedvox commented on src/controller/index.ts
> +      && this.engine.windows.getVisibleTiles(window.surface).includes(window)) {
`getVisibleTiles().incudes(window)` is checking that the active window is not floating. Perhaps a shorthand function would be more readable.

2021-09-30 00:31 UTC, bladedvox commented on src/controller/index.ts
> +      this.engine.currentLayoutOnCurrentSurface().apply(
When switching to a window that has not yet been focused with this layout, this makes sure the window's geometry gets changed when it's unminimized.

2021-09-30 00:32 UTC, bladedvox commented on src/engine/index.ts
> +        && this.config.monocleMinimizeRest && this.controller.currentWindow) {
I think layout handlers are a good idea. As for a wrapper for the meantime, would something like `isMonocleLayoutAndMinimizeRest()` work? It's still verbose but not quite as bad.

2021-09-30 02:04 UTC, bladedvox commented
Addressed the issues you mentioned, got the husky hooks set up, verified with ESLint (apparently if you have a default parameter in a function, you don't need to declare its type, good to know) and formatted with Prettier. Rebuilt and restarted KWin for good measure. Everything seems good on my end!

2021-09-30 11:38 UTC, gikari approved these changes
Hm, I noticed another thing - if I switch to another layout, the windows, that were minimized by the script are not brought back. I think this, can be addressed in another PR. For now, it is good.

2021-09-30 11:38 UTC, gikari commented on src/engine/index.ts
> +  /** Focus next or previous window
You don't have to duplicate JSDoc here.

2021-09-30 11:47 UTC, merged